### PR TITLE
Fix link in README

### PR DESCRIPTION
**Pull request by hemajv**
update link for user docs

### CODE REVIEW

**Comment by anishasthana** [comment]
Should the link be pointed to a gatsby url?

**Comment by HumairAK** [comment]
@harshad16  we're seeing `aicoe-ci/build-check` in this repo's pr's, even though it's not in the ci files.

**Review by HumairAK — APPROVED** [review]

**Comment by hemajv** [comment]
> Should the link be pointed to a gatsby url?

no, we will just need to add this repo as a remote repo for gatsby to pull/render the docs

**Comment by harshad16** [comment]
> @harshad16 we're seeing `aicoe-ci/build-check` in this repo's pr's, even though it's not in the ci files.

Thanks for pointing :+1:

**Pull request merged**
